# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

services:
  - postgresql

# используем режим обычного пользователя для сборки проекта.
sudo: false

before_install:
  - psql -c 'create database tracker;' -U postgres


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman.mozhaev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="d8749a7d-9963-4935-a4c3-59026e102de2"
